// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: csharp/service/test.proto
using Service;
using FluentValidation;

namespace Service
{
    public class PersonValidator : AbstractValidator<Person>
    {
        public PersonValidator()
        {
            RuleFor(msg => msg.ID).NotEmpty();
            RuleFor(msg => msg.Email).NotEmpty();
            RuleFor(msg => msg.Name).NotEmpty();
            RuleFor(msg => msg.Home).NotEmpty();
        }
    }

    public class Person_LocationValidator : AbstractValidator<Person.Types.Location>
    {
        public Person_LocationValidator()
        {
            RuleFor(msg => msg.Lat).NotEmpty();
            RuleFor(msg => msg.Lng).NotEmpty();
        }
    }

}
